package com.homer.unittestcases;

import org.junit.Assert;
import org.junit.Test;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import com.homer.dao.CommonData;
import com.homer.dao.DataClass;
import com.homer.dao.InstanceContainer;
import com.homer.helper.DataTable;
import com.homer.helper.ExcelDataTable;
import com.homer.po.Login;
import com.homer.po.PageBase;
import com.homer.reports.HTMLReport;
import com.homer.reports.HTMLSummaryReport;
import com.homer.reports.Report;
import com.homer.resuablecomponents.ReusableComponents;
import com.homer.resuablecomponents.WebDriverHelper;

/**
 * The class <code>LoginDefnTest</code> contains tests for the class {@link <code>LoginDefn</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 5/9/16 2:29 PM
 *
 * @author MXN8002
 *
 * @version $Revision$
 */
public class LoginTest {
//public class LoginDefnTest extends TestCase { 
	/**
	 * Construct new test instance
	 *
	 * @param name
	 *            the test name
	 */
	
	
	public LoginTest() {
		
	}
	
	/**
	 * Run the void Username_and_password() method test
	 */
	@Test
	public void testLoginToAppl() {
		
		try {
			System.setProperty("webdriver.chrome.driver", "C:\\testAutomationWorkspace\\Homer-ClearCadence\\Drivers\\chromedriver.exe");

		WebDriver driver= new ChromeDriver();
		//Report report = new Report();
		Report report = null;
		DataTable dataTable = new ExcelDataTable();
		WebDriverHelper wh = new WebDriverHelper(driver, report, dataTable);
		ReusableComponents rc = new ReusableComponents(driver, report, wh, dataTable); 
		CommonData commonData = new CommonData();
		
		InstanceContainer ic = new InstanceContainer(driver,report,dataTable,
				wh, rc, commonData);
		Login loginObj = new Login(ic);
		
		loginObj.setUserName("gxr2934");
		loginObj.setPassword("qa02test");
		loginObj.clickLogin();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		String message = "Clearance Optimization Maintenance";
		Assert.assertEquals("Clearance Optimization Maintenance",message);
		
	}
}

/*
 * $CPS$ This comment was generated by CodePro. Do not edit it. patternId =
 * com.instantiations.assist.eclipse.pattern.testCasePattern strategyId =
 * com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = assertTrue = false callTestMethod = true createMain =
 * false createSetUp = false createTearDown = false createTestFixture = false
 * createTestStubs = true methods = Username_and_password() package =
 * com.homer.glue package.sourceFolder = Homer-ClearCadence/src/main/java
 * superclassType = junit.framework.TestCase testCase = LoginDefnTest
 * testClassType = com.homer.glue.LoginDefn
 */